// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbrttrvqtojrznpioswt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhicnR0cnZxdG9qcnpucGlvc3d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjQyMTcsImV4cCI6MjA2MDIwMDIxN30.NqqxygoUZea4N9_-Wd2U3tgOojrnDLFbU2R8PNeJbkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);